version: '3.4'
services:
  cppapp:
    entrypoint: /bin/bash
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=caleb
    command:  -c "sleep infinity"
    user: caleb
    volumes:
      - ./:/Project